In [2]:
import numpy

In [3]:
import numpy as np
print(np.__version__)

2.2.6


### zero dimensional array-which consists of single value with no axis
a=np.array(10)
print(a)
#we can create any sequence like list tuple etc into numpy array using np.array(),np.asarray(),np.frombuffer(),np.fromiter()

In [5]:
#one dimensional array-contains a sequence of elemnts arranged in a single line  with one axis
a=np.array([10,20,30])
print(a)

[10 20 30]


In [6]:
#two dimensional array-an array with rows and columns consist of two axis one for rows and other for columns
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [7]:
print(a[1][2])

60


In [9]:
#three dimensional array-collection of two dimensions
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [11]:
print(a[0][1][0])

30


In [7]:
#asarray function is used to convert list tuple or other to numpy array and the elements are converted into other datatype by dtype
#asarray(input that need to be converted into an array,datatype
a=[10,20,30]
b=np.asarray(a,dtype=float)
print(b)

[10. 20. 30.]


In [6]:
#the order parameter in npasarray() function specifies how multidimensional data stored in memory.'C'-row major order 'D'-column major order
a=[[10,20],[30,40]]
b=np.asarray(a,order='C')

In [10]:
#ndim-is aattribute used to print the dimensions of the array 
a=np.array(10)
b=np.array([[10,20],[30,40]])
print(a.ndim)
print(b.ndim)

0
2
[[[[[1 2 3 4]]]]]


In [14]:
print(b)

[[10 20]
 [30 40]]


In [15]:
#The np.nditer() function in NumPy is a multidimensional iterator used to efficiently loop through elements of a NumPy array
for i in np.nditer(b):
    print(i)

10
20
30
40


In [16]:
a=[[10,20],[30,40]]
b=np.asarray(a,order='F')

In [12]:
for i in np.nditer(b):
    print(i)

10
30
20
40


In [17]:
#The numpy.frombuffer() function is used to interpret a buffer (like bytes or bytearray) as a 1-dimensional NumPy array. It's especially useful when working with binary data, files, or data coming from external sources
'''parameters
1.buffer-A buffer object (like bytes, bytearray, or memory-mapped file).
2.dtype: Data type of the array you want to interpret the buffer as. Default is float
3.count: Number of items to read. Default is -1 (read all).
offset: Start reading from this byte offset in the buffer.'''
a=b'Welcome to numpy'
b=np.frombuffer(a,dtype='S1',count=2,offset=9)

In [18]:
print(b)

[b'o' b' ']


In [19]:
#The numpy.fromiter() function is used to create a 1D NumPy array from any iterable, such as a list, tuple, generator, or any object that returns elements one at a time.
a=[10,20,30,40]
b=np.fromiter(a,dtype=int,count=2)

In [20]:
print(b)

[10 20]


In [21]:
#initializing the arrays

In [24]:
#zeros()-Create an array of given shape and dtype, filled entirely with zeros.
a=np.zeros(3,dtype=int)
print(a)

[0 0 0]


In [26]:
np.zeros([2,3])


array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#fill()-Create an array of given shape and dtype, filled with the value you specify.
a=np.full([2,3],1,dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


In [32]:
np.random.rand(2,3)

array([[0.32364893, 0.9000614 , 0.81052426],
       [0.34059052, 0.7827747 , 0.72922867]])

In [33]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
#The numpy.eye() function creates a 2D identity matrix — a square matrix with ones on the main diagonal and zeros elsewhere.
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [5]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
#numerical ranges

In [37]:
np.arange(10,20,1,dtype=int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
np.arange(0,100,20,dtype=float)

array([ 0., 20., 40., 60., 80.])

In [40]:
a=np.arange(10,70,10,dtype=int)

In [41]:
print(a)

[10 20 30 40 50 60]


In [42]:
a.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
#linespace()-np.linspace() is used to create a 1D array of evenly spaced numbers over a specified interval.
'''Parameter	Description
start-The starting value of the sequence.
stop-The end value of the sequence.
num-Number of samples to generate. Default is 50.
endpoint-If True (default), stop is included; otherwise, it's excluded.
retstep-If True, returns a tuple: (array, step size).
dtype-Data type of the output array.'''
a=np.linspace(10,100,10)   #here 10 is the number of intervels we have to divide

In [45]:
print(a) #endpoint is also included

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [49]:
b=np.linspace(10,100,10,endpoint=False,dtype=int,retstep=True)
print(b)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), np.float64(9.0))


In [3]:
np.logspace(1,10,10,base=2)  #default will be base 10

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [4]:
a=np.arange(10,100,10)
print(a)

[10 20 30 40 50 60 70 80 90]


In [5]:
a=a.reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#Array Properties(1.size-np.size(array)  2.shape-np.shape(array)   3.data type  np.dtype(array)


In [6]:
np.size(a)  #total number of elements

9

In [7]:
np.shape(a)

(3, 3)

In [9]:
a.dtype

dtype('int64')

In [ ]:
#<-------Array Operations------->

In [11]:
#acessing and slicing operations
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [16]:
print(a[0])
print(a[1])
print(a[0][1])
print(a[1][2])

[10 20 30]
[40 50 60]
20
60


In [17]:
#copying
b=np.copy(a)
print(a)

[[10 20 30]
 [40 50 60]]


In [18]:
#sort
a=np.array([30,10,90,50,40])
np.sort(a)

array([10, 30, 40, 50, 90])

In [20]:
a=np.array([[40,30,20],[10,50,5]])
print(a)

[[40 30 20]
 [10 50  5]]


In [21]:
np.sort(a,axis=0)  #when axisis is zero the sorting is column based when axisis is one it is rowwise

array([[10, 30,  5],
       [40, 50, 20]])

In [22]:
np.sort(a)   #row wise sorting

array([[20, 30, 40],
       [ 5, 10, 50]])

In [5]:
d=np.dtype([('name','S1'),('marks',float)])
a=np.array([('harika',98.0),('meghana',90.0)],dtype=d)
a

array([(b'h', 98.), (b'm', 90.)], dtype=[('name', 'S1'), ('marks', '<f8')])

In [6]:
np.sort(a,order='name')

array([(b'h', 98.), (b'm', 90.)], dtype=[('name', 'S1'), ('marks', '<f8')])

In [7]:
np.sort(a,order='marks')

array([(b'm', 90.), (b'h', 98.)], dtype=[('name', 'S1'), ('marks', '<f8')])

In [8]:
#reshape()
a=np.arange(10,110,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [11]:
a.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [12]:
a.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [13]:
a=np.arange(10,130,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [14]:
a.reshape(6,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120]])

In [15]:
a.reshape(2,6)

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [16]:
a.reshape(4,3)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [17]:
a.reshape(2,3,2)

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]]])

In [21]:
#append-adding two lists
a=np.array([10,20,30])
b=np.array([40,60,50])
c=np.append(a,b)
c=np.sort(c)
print(c)

[10 20 30 40 50 60]


In [22]:
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
c=np.append(a,b)
print(c)

[10 20 30 40 50 60 70 80]


In [25]:
#insert:np.insert(array,position,element)
a=np.array([[10,20],[30,40]])
a=np.insert(a,3,35)
print(a)

[10 20 30 35 40]


In [26]:
np.insert(a,3,[50,60,70])

array([10, 20, 30, 50, 60, 70, 35, 40])

In [27]:
#delete---np.delete(array,index)
np.delete(a,2)

array([10, 20, 35, 40])

In [ ]:
# when ever we are aplying delete or insert operations on multidimensional array it will return as single dimensional array

In [5]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[70,75,80],[85,90,96]])
np.concat((a,b))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 75, 80],
       [85, 90, 96]])

In [6]:
np.concat((a,b),axis=1)

array([[10, 20, 30, 70, 75, 80],
       [40, 50, 60, 85, 90, 96]])

In [7]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
b

array([[70, 75, 80],
       [85, 90, 96]])

In [9]:
#stack
res=np.stack((a,b))
print(res)

[[[10 20 30]
  [40 50 60]]

 [[70 75 80]
  [85 90 96]]]


In [10]:
res[0]  #first array that is a will be printed

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
res[1]  #second array that is b will be printed

array([[70, 75, 80],
       [85, 90, 96]])

In [12]:
#the main difference between concat and stack is np.concat() joins two or more arrays along an exsisting axis where as np.stack() joins array along new axis

In [13]:
np.stack((a,b),axis=1) 

array([[[10, 20, 30],
        [70, 75, 80]],

       [[40, 50, 60],
        [85, 90, 96]]])

In [16]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
b

array([[70, 75, 80],
       [85, 90, 96]])

In [14]:
#vstack
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 75, 80],
       [85, 90, 96]])

In [15]:
#hstack
np.hstack((a,b))   #concatination with respect to axsis 1

array([[10, 20, 30, 70, 75, 80],
       [40, 50, 60, 85, 90, 96]])

In [18]:
np.concat((a,b),axis=1)

array([[10, 20, 30, 70, 75, 80],
       [40, 50, 60, 85, 90, 96]])

In [19]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
b

array([[70, 75, 80],
       [85, 90, 96]])

In [21]:
np.dstack((a,b))

array([[[10, 70],
        [20, 75],
        [30, 80]],

       [[40, 85],
        [50, 90],
        [60, 96]]])

In [22]:
#concat() stack() vstack() hstack() dstack() are all used for joining arrays in different ways

In [23]:
#np.split() function is udes to split the array into multiple sub arrays
x=np.arange(10,110,10)
print(x)

[ 10  20  30  40  50  60  70  80  90 100]


In [24]:
np.split(x,5)  #splits the arryas with each array contains 5 elements

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [25]:
np.split(x,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [26]:
a1,a2,a3,a4,a5=np.split(x,5)
print(a1)
print(a2)
print(a3)
print(a4)

[10 20]
[30 40]
[50 60]
[70 80]


In [27]:
a=np.arange(10,120,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100 110]


In [30]:
np.split(a,(2,6))

[array([10, 20]), array([30, 40, 50, 60]), array([ 70,  80,  90, 100, 110])]

In [ ]:
#where() function is used to check where the elements is present in the array

In [32]:
a=np.arange(10,130,10).reshape(4,3)
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [33]:
np.where(a==80) #present in second row and first column

(array([2]), array([1]))

In [34]:
a=np.arange(10,110,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
np.where(a==40)

(array([3]),)

In [36]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [37]:
np.where(a%20==0)  #1st index is 20 3rd index is 40 5th index 60 7th index is 80 9th index is 100 all are divisible by 20

(array([1, 3, 5, 7, 9]),)

In [40]:
#searchsort--search in a sorted array and returns the index
a=np.array([10,20,30,40,50,60])
np.searchsorted(a,20)

np.int64(1)

In [41]:
np.searchsorted(a,[40,50,60])

array([3, 4, 5])

In [ ]:
#Arithmetic operations(when ever we are doing any arithmetic operations the size of both arrays should match except for multiplication for multiplication
#the number of columns of first array should be same as the number of rows of the second array

In [43]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [45]:
np.subtract(a,b)

array([[ 9, 18, 27],
       [36, 45, 54]])

In [46]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [47]:
np.divide(a,b)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [48]:
np.exp(a)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]])

In [49]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [50]:
np.sqrt(a)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [51]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
a=np.array([10,20,30])
b=np.array([10,20,30])
np.array_equal(a,b)

True

In [ ]:
#Array function(sum,mean,median,standarddeviation,varience,max,min)

In [54]:
a=np.array([[10,20],[30,40],[50,60]])
np.min(a)

np.int64(10)

In [55]:
np.max(a)

np.int64(60)

In [56]:
np.min(a,axis=1)

array([10, 30, 50])

In [57]:
np.min(a,axis=0)

array([10, 20])

In [58]:
np.max(a)

np.int64(60)

In [59]:
np.max(a,axis=1)

array([20, 40, 60])

In [60]:
np.max(a,axis=0)

array([50, 60])

In [61]:
np.sum(a)

np.int64(210)

In [62]:
np.sum(a,axis=1)

array([ 30,  70, 110])

In [63]:
np.sum(a,axis=0)

array([ 90, 120])

In [64]:
np.mean(a)

np.float64(35.0)

In [65]:
np.mean(a,axis=0)

array([30., 40.])

In [66]:
np.mean(a,axis=1)

array([15., 35., 55.])

In [67]:
np.median(a)

np.float64(35.0)

In [68]:
np.var(a)

np.float64(291.6666666666667)

In [69]:
np.std(a)

np.float64(17.07825127659933)